export const postAction = {
  GET_ALL_POST_SUCCESS: "GET_ALL_POST_SUCCESS",
  GET_ALL_POST: "GET_ALL_POST",
  LIKE_POST: "LIKE_POST",
  SHARE_POST: "SHARE_POST",
  COMMENT_POST: "COMMENT_POST",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  DELETE_IMAGE_POST: "DELETE_IMAGE_POST",
  GET_ALL_POST_PERSONEL: "GET_ALL_POST_PERSONEL",
  GET_ALL_POST_PERSONEL_SUCCESS: "GET_ALL_POST_PERSONEL_SUCCESS",
};
