export const postAction = {
  GET_ALL_POST_SUCCESS: "GET_ALL_POST_SUCCESS",
  GET_ALL_POST: "GET_ALL_POST",
  LIKE_POST: "LIKE_POST",
  SHARE_POST: "SHARE_POST",
  COMMENT_POST: "COMMENT_POST",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  DELETE_IMAGE_POST: "DELETE_IMAGE_POST",
  GET_ALL_POST_PERSONEL: "GET_ALL_POST_PERSONEL",
  GET_ALL_POST_PERSONEL_SUCCESS: "GET_ALL_POST_PERSONEL_SUCCESS",
  UPDATE_COMMENT: "UPDATE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT"
};

export const userAction = {
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  GET_ALL_USER: "GET_ALL_USER",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
}

export const studySpaceAction = {
  GET_ALL_GROUP: "GET_ALL_GROUP",
  GET_ALL_GROUP_SUCCESS: "GET_ALL_GROUP_SUCCESS",
  CREATE_NEW_GROUP: "CREATE_NEW_GROUP",
  UPDATE_GROUP: "UPDATE_GROUP",
  DELETE_GROUP: "DELETE_GROUP",
  ADD_NEW_MEMBER: "ADD_NEW_MEMBER",
  DELETE_MEMBER: "DELETE_MEMBER",
  LEAVE_GROUP: "LEAVE_GROUP",
  CREATE_NEW_TOPIC: "CREATE_NEW_TOPIC",
  GET_TOPIC_BY_ID: "GET_TOPIC_BY_ID",
  GET_TOPIC_BY_ID_SUCCESS: "GET_TOPIC_BY_ID_SUCCESS",
  UPDATE_TOPIC: "UPDATE_TOPIC",
  DELETE_TOPIC: "DELETE_TOPIC",
  CREATE_NEW_PROBLEM: "CREATE_NEW_PROBLEM",
  UPDATE_PROBLEM: "UPDATE_PROBLEM",
  DELETE_PROBLEM: "DELETE_PROBLEM",
  CREATE_NEW_SOLUTION: "CREATE_NEW_SOLUTION",
  UPDATE_SOLUTION: "UPDATE_SOLUTION",
  DELETE_SOLUTION: "DELETE_SOLUTION",
}

export const followAction = {
  ADD_FOLLOW: "ADD_FOLLOW",
  GET_LIST_FOLLOW: "GET_LIST_FOLLOW",
  GET_LIST_FOLLOW_SUCCESS: "ADD_FOLLOW_SUCCESS",
  REMOVE_FOLLOW: "REMOVE_FOLLOW",
}

export const messageAction = {
  SEND_MESSAGE: "SEND_MESSAGE",
  CREATE_CONVERSATION: "CREATE_CONVERSATION",
  GET_ONE_CONVERSATION: "GET_ONE_CONVERSATION",
  GET_ONE_CONVERSATION_SUCCESS: "GET_ONE_CONVERSATION_SUCCESS",
  GET_ALL_MESSAGE: "GET_ALL_MESSAGE",
  GET_ALL_MESSAGE_SUCCESS: "GET_ALL_MESSAGE_SUCCESS",
  GET_MESSAGE_BY_CONVERSATION: "GET_MESSAGE_BY_CONVERSATION",
  GET_MESSAGE_BY_CONVERSATION_SUCCESS: "GET_MESSAGE_BY_CONVERSATION_SUCCESS",
  UPDATE_STATUS_MESSAGE: "UPDATE_STATUS_MESSAGE",
  GET_CONVERSATION_BY_USER: "GET_CONVERSATION_BY_USER",
  GET_CONVERSATION_BY_USER_SUCCESS: "GET_CONVERSATION_BY_USER_SUCCESS",
}